package: diff_detect
version: '0.0.0'
author: Robert Rupf
supportpage: https://github.com/xong/redaxo_diff_detect
requires:
    redaxo: '^5.15.1'
    packages:
        yform: '>=4.1.0'
        cronjob: '>=2.10.0'
    php:
        version: '>=8.2'

page:
    title: Diff Detection
    perm: diff_detect[]
    pjax: true
    icon: rex-icon rex-icon-table
    subpages:
        dashboard:
            title: 'translate:dashboard'
        intervals:
            title: 'translate:intervals'
        filter:
            title: 'translate:filter'
#        settings:
#            title: 'Einstellungen'
#            perm: diff_detect[settings]
