package: diff_detect
version: '1.12'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/diff_detect
requires:
    redaxo: '^5.15.1'
    packages:
        yform: '>=3.2,<6.0.0-dev'
        cronjob: '>=2.10.0'
    php:
        version: '>=8.2'

page:
    title: Diff Detection
    perm: diff_detect[]
    icon: rex-icon rex-icon-table
    subpages:
        dashboard:
            title: 'translate:dashboard'
        settings:
            title: 'translate:settings'

console_commands:
    diff_detect:execute: \FriendsOfRedaxo\DiffDetect\Command\Console

installer_ignore:
    - .github
    - .gitignore
    - assets/backend.scss
    - assets/backend.css.map
    - assets/table.scss
    - assets/table.css.map
