package: diff_detect
version: '1.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/diff_detect
requires:
    redaxo: '^5.15.1'
    packages:
        yform: '>=4.1.0'
        cronjob: '>=2.10.0'
    php:
        version: '>=8.2'

page:
    title: Diff Detection
    perm: diff_detect[]
    icon: rex-icon rex-icon-table
    subpages:
        dashboard:
            title: 'translate:dashboard'

installer_ignore:
    - .github
    - .gitignore
    - .php-cs-fixer.dist.php
    - composer.json
    - composer.lock
    - assets/backend.scss
    - assets/backend.css.map
    - assets/table.scss
    - assets/table.css.map
